version: '3'
services:
  db:
    container_name: "second_test_db"
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment: # postgresql://test2:test2pwd@localhost:5432/test2db?schema=public
      POSTGRES_USER: test2
      POSTGRES_PASSWORD: test2pwd
      POSTGRES_DB: test2db
  couriers_api:
    container_name: "second_test_couriers_api"
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:3000
    environment:
      DATABASE_URL: postgresql://test2:test2pwd@db:5432/test2db?schema=public
      PORT: 3000
      NODE_ENV: production
    depends_on:
      - db
